### ISSUE TITLE
SRD built with DSH 4.0.4 has failing smoke tests for torch with Python 3.9 and 3.11 (but not 3.10)

### ISSUE THREAD

**Issue by edwardchalstrey1** [alan-turing-institute/data-safe-haven#1458]
## :white_check_mark: Checklist

- [x] I have searched open and closed issues for duplicates.
- [x] This is a problem observed when **deploying** a Data Safe Haven.
- [x] I can reproduce this with the [latest version](https://github.com/alan-turing-institute/data-safe-haven/releases).
- [x] I have read through the [documentation](https://alan-turing-institute.github.io/data-safe-haven/).
- [x] This isn't an open-ended question (open a [discussion](https://github.com/alan-turing-institute/data-safe-haven/discussions) if it is).

## :computer: System information

- **Operating System:** mac
- **Data Safe Haven version:** 4.0.4

## :no_entry_sign: Describe the problem

I've built a new SRD image called `20.04.2023050900` hosted at the image gallery for the `prod4` SHM at Turing.

Running `run_all_tests.bats` as per the [deployment docs](https://alan-turing-institute.github.io/data-safe-haven/develop/deployment/deploy_sre_apache_guacamole.html#run-smoke-tests-on-srd) shows that there are 2 failures, for Python packages where the `torch` package appears to be the issue, and something to do with CUDA:

```
ValueError: libcublas.so.*[0-9] not found in the system path ['/opt/tests/tests' ...
```
- See full error message below. Weird that this doesn't occur with Python 3.10, but does with 3.9 and 3.11
- Also, even on Python 3.9 and 3.11, it is possible to pip install torch and import it without issue
- When I resize the SRD to a GPU VM and log in to run `nvidia-smi` there is no problem either

## :deciduous_tree: Log messages

<details>
<summary>Relevant log messages</summary>

```none
✗ Python packages (3.11)
   (from function `assert_output' in file ../bats/bats-assert/src/assert_output.bash, line 178,
    from function `test_python_packages' in file run_all_tests.bats, line 30,
    in test file run_all_tests.bats, line 96)
     `test_python_packages '3.11'' failed
   
   -- regular expression does not match output --
   regexp (1 lines):
     All [0-9]+ packages are installed
   output (37 lines):
     Python version 3.11.3 found
     Testing 56 Python packages
     Testing 'arviz' ...
     Testing 'beautifulsoup4' ...
     Testing 'black' ...
     Testing 'Cython' ...
     Testing 'dash' ...
     Testing 'dask' ...
     Testing 'flair' ...
     Traceback (most recent call last):
       File "/home/ed.chalstrey1/.pyenv/versions/3.11.3/lib/python3.11/site-packages/torch/__init__.py", line 168, in _load_global_deps
         ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
       File "/home/ed.chalstrey1/.pyenv/versions/3.11.3/lib/python3.11/ctypes/__init__.py", line 376, in __init__
         self._handle = _dlopen(self._name, mode)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
     OSError: libcufft.so.10: cannot open shared object file: No such file or directory
   
     During handling of the above exception, another exception occurred:
   
     Traceback (most recent call last):
       File "/opt/tests/tests/test_packages_installed_python.py", line 153, in <module>
         test_packages()
       File "/opt/tests/tests/test_packages_installed_python.py", line 141, in test_packages
         warning, missing = get_missing_packages(packages)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       File "/opt/tests/tests/test_packages_installed_python.py", line 107, in get_missing_packages
         _ = __import__(importable_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
       File "/home/ed.chalstrey1/.pyenv/versions/3.11.3/lib/python3.11/site-packages/flair/__init__.py", line 5, in <module>
         import torch
       File "/home/ed.chalstrey1/.pyenv/versions/3.11.3/lib/python3.11/site-packages/torch/__init__.py", line 228, in <module>
         _load_global_deps()
       File "/home/ed.chalstrey1/.pyenv/versions/3.11.3/lib/python3.11/site-packages/torch/__init__.py", line 189, in _load_global_deps
         _preload_cuda_deps(lib_folder, lib_name)
       File "/home/ed.chalstrey1/.pyenv/versions/3.11.3/lib/python3.11/site-packages/torch/__init__.py", line 154, in _preload_cuda_deps
         raise ValueError(f"{lib_name} not found in the system path {sys.path}")
     ValueError: libcublas.so.*[0-9] not found in the system path ['/opt/tests/tests', '/home/ed.chalstrey1/.pyenv/versions/3.11.3/lib/python311.zip', '/home/ed.chalstrey1/.pyenv/versions/3.11.3/lib/python3.11', '/home/ed.chalstrey1/.pyenv/versions/3.11.3/lib/python3.11/lib-dynload', '/home/ed.chalstrey1/.local/lib/python3.11/site-packages', '/home/ed.chalstrey1/.pyenv/versions/3.11.3/lib/python3.11/site-packages']

```

</details>

## :recycle: To reproduce

Deploy an SRE with `20.04.2023050900` or another image generated from `release-v4.0.4` branch in the config file and log in as a user, then run smoke tests

**Comment by edwardchalstrey1** [comment]
Interesting, I just switched to a GPU VM and ran the smoke tests again, now Python 3.9 passes all tests... but not 3.11 - seems like it's probably unrelated.

Don't think this is a blocker to using 4.0.4 for the DSG, however might be worth investigating before release
